/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SwiperOptions } from "swiper/types/swiper-options";
import { PaginationOptions } from "swiper/types/components/pagination";
export namespace Components {
    interface ContentSlider {
        "options": SwiperOptions | string;
        "paginationOptions": PaginationOptions | string;
        "target": string;
    }
    interface PocNavDrawer {
    }
    interface PocNavMenuItem {
        "icon": string;
    }
}
declare global {
    interface HTMLContentSliderElement extends Components.ContentSlider, HTMLStencilElement {
    }
    var HTMLContentSliderElement: {
        prototype: HTMLContentSliderElement;
        new (): HTMLContentSliderElement;
    };
    interface HTMLPocNavDrawerElement extends Components.PocNavDrawer, HTMLStencilElement {
    }
    var HTMLPocNavDrawerElement: {
        prototype: HTMLPocNavDrawerElement;
        new (): HTMLPocNavDrawerElement;
    };
    interface HTMLPocNavMenuItemElement extends Components.PocNavMenuItem, HTMLStencilElement {
    }
    var HTMLPocNavMenuItemElement: {
        prototype: HTMLPocNavMenuItemElement;
        new (): HTMLPocNavMenuItemElement;
    };
    interface HTMLElementTagNameMap {
        "content-slider": HTMLContentSliderElement;
        "poc-nav-drawer": HTMLPocNavDrawerElement;
        "poc-nav-menu-item": HTMLPocNavMenuItemElement;
    }
}
declare namespace LocalJSX {
    interface ContentSlider {
        "onSliderInit"?: (event: CustomEvent<SwiperCore>) => void;
        "options"?: SwiperOptions | string;
        "paginationOptions"?: PaginationOptions | string;
        "target"?: string;
    }
    interface PocNavDrawer {
    }
    interface PocNavMenuItem {
        "icon": string;
    }
    interface IntrinsicElements {
        "content-slider": ContentSlider;
        "poc-nav-drawer": PocNavDrawer;
        "poc-nav-menu-item": PocNavMenuItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "content-slider": LocalJSX.ContentSlider & JSXBase.HTMLAttributes<HTMLContentSliderElement>;
            "poc-nav-drawer": LocalJSX.PocNavDrawer & JSXBase.HTMLAttributes<HTMLPocNavDrawerElement>;
            "poc-nav-menu-item": LocalJSX.PocNavMenuItem & JSXBase.HTMLAttributes<HTMLPocNavMenuItemElement>;
        }
    }
}
